Repository securesign/trillian, pull requests merged in 2023-10, with the labels that each got.

#6 :robot: triggering CI on branch 'redhat-v1.5.2' after synching from upstream/v1.5.2
  ci
Labels: kind/sync-fork-to-upstream, ok-to-test

#40 chore: don't force push the release branch
  redhat/release/update-to-head.sh
Labels: approved

#50 chore: modify update script to avoid merge conflicts
  redhat/release/update-to-head.sh
Labels: lgtm, approved

#49 Trillian enterprise contracts
  .tekton/trillian-database-pull-request.yaml
  .tekton/trillian-database-push.yaml
  .tekton/trillian-logserver-pull-request.yaml
  .tekton/trillian-logserver-push.yaml
  .tekton/trillian-logsigner-pull-request.yaml
  .tekton/trillian-logsigner-push.yaml
  .tekton/trillian-netcat-pull-request.yaml
  .tekton/trillian-netcat-push.yaml
Labels: ok-to-test, lgtm

#46 Adding labels for the trillian Enterprise Contract
  redhat/overlays/Dockerfile.database
  redhat/overlays/Dockerfile.logserver
  redhat/overlays/Dockerfile.logsigner
  redhat/overlays/Dockerfile.netcat
Labels: lgtm, approved

#57 Update script
  redhat/release/update-to-head.sh
Labels: lgtm, approved

#61 chore: Adds new com.redhat.component label
  redhat/overlays/Dockerfile.database
  redhat/overlays/Dockerfile.logserver
  redhat/overlays/Dockerfile.logsigner
  redhat/overlays/Dockerfile.netcat
Labels: lgtm

#63 chore: update image refs for all Dockerfiles
  redhat/overlays/Dockerfile.database
  redhat/overlays/Dockerfile.logserver
  redhat/overlays/Dockerfile.logsigner
  redhat/overlays/Dockerfile.netcat
Labels: lgtm, approved

#66 Removing NetCat Hermetic Build
  .tekton/trillian-netcat-pull-request.yaml
  .tekton/trillian-netcat-push.yaml
  Dockerfile.netcat
Labels: ok-to-test, lgtm

#65 :robot: triggering CI on branch redhat-v1.5.2 after synching from upstream/v1.5.2
  Dockerfile.database
  Dockerfile.logserver
  Dockerfile.logsigner
  Dockerfile.netcat
  redhat/overlays/Dockerfile.database
  redhat/overlays/Dockerfile.logserver
  redhat/overlays/Dockerfile.logsigner
  redhat/overlays/Dockerfile.netcat
Labels: kind/sync-fork-to-upstream, lgtm

#68 feat: Add GH action
  .github/workflows/cronjobs.yaml
Labels: lgtm
