Repository securesign/trillian, pull requests merged in 2024-08, with the labels that each got.

#257 chore: SECURESIGN-1245 multi-arch builds
  Build-clis.mak
  Dockerfile.createtree.rh
  Dockerfile.updatetree.rh
Labels: lgtm

#260 fix(KONFLUX-3663): format PipelineRun files and upload SAST results
  .tekton/createtree-pull-request.yaml
  .tekton/createtree-push.yaml
  .tekton/database-pull-request.yaml
  .tekton/database-push.yaml
  .tekton/logserver-pull-request.yaml
  .tekton/logserver-push.yaml
  .tekton/logsigner-pull-request.yaml
  .tekton/logsigner-push.yaml
  .tekton/redis-pull-request.yaml
  .tekton/redis-push.yaml
  .tekton/updatetree-pull-request.yaml
  .tekton/updatetree-push.yaml
Labels: ok-to-test

#197 Switch Pipelines to use Trusted Artifact
  .tekton/database-pull-request.yaml
  .tekton/database-push.yaml
  .tekton/logserver-pull-request.yaml
  .tekton/logserver-push.yaml
  .tekton/logsigner-pull-request.yaml
  .tekton/logsigner-push.yaml
  .tekton/redis-pull-request.yaml
  .tekton/redis-push.yaml
  .tekton/trillian-unit-test.yaml
Labels: ok-to-test, lgtm
